[package]
name = "uring-rt"
version = "0.1.0"
edition = "2024"





[dependencies]
aio-macros = {path = "../aio-macros"}
futures = "0.3.31"
io-uring = "0.7.9"
libc = "0.2.174"
nix = { version = "0.30.1", features = ["event"] }
slab = "0.4.10"

# num_cpus = "1.17.0"

